TEMPLATE = app
QT = gui core
CONFIG += qt debug warn_on console
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/mainwindowimpl.ui ui/mapoporfunkcio.ui
HEADERS = src/mainwindowimpl.h src/bazomapo.h src/funkcio.h
SOURCES = src/mainwindowimpl.cpp src/main.cpp src/bazomapo.cpp
